/**
 * Crée / met à jour la page marketing CMS `home` (urlPath `/`) avec sections + contenus FR publiés.
 *
 * Prérequis : DB accessible (DATABASE_URL), médias optionnels sous public/images/*.png
 *
 * Exécution :
 *   cd services/arquantix/web && npx tsx scripts/seed-cms-home.ts
 *   # ou : npm run db:seed:cms-home
 */

import { PrismaClient, ContentStatus, Prisma } from '@prisma/client'

const prisma = new PrismaClient()

const PAGE_SLUG = 'home'

const SECTIONS: Array<{ key: string; order: number; data: Prisma.InputJsonObject }> = [
  {
    key: 'hero',
    order: 0,
    data: {
      title:
        'Premium Real Estate Yield,\nDelivered On-Chain.',
      subtitle:
        'Earn reliable yield backed by premium real estate operations. Built with institutional-grade transparency and real asset backing.',
      ctaText: 'Call to action whatsapp',
      ctaLink: 'https://wa.me/6281353009603',
    },
  },
  {
    key: 'about_showcase',
    order: 1,
    data: {
      title: '',
      description: '',
      imageUrl: '/images/dashboard.png',
    },
  },
  {
    key: 'projects',
    order: 2,
    data: {
      eyebrow: '',
      title: 'Exclusive offers.',
      description:
        'Institutional-grade real estate investments, now accessible from €1,000',
      selectedPackagedProductIds: [],
    },
  },
  {
    key: 'how_it_works',
    order: 3,
    data: {
      label: 'HOW IT WORKS',
      title: '',
      subtitle: '',
      surface: 'light',
      steps: [
        {
          number: '01',
          title: 'Access the platform',
          description:
            "Create an account or connect a wallet. A simple, secure onboarding. In a few guided steps, you're in.",
        },
        {
          number: '02',
          title: 'Explore the Projects',
          description:
            'Browse curated real estate projects with full documentation: location, expected return, maturity, risk profile. Everything you need to decide with confidence.',
        },
        {
          number: '03',
          title: 'Deposit and Start Earning',
          description:
            'Choose a project, deposit in one click, and start earning immediately. Your returns are backed by real assets.',
        },
      ],
      primaryCtaText: 'START EARNING',
      primaryCtaHref: '#projects',
    },
  },
  {
    key: 'about_transparency',
    order: 4,
    data: {
      title: 'Transparency is not optional.',
      description:
        'All investments include full documentation, legal clarity, and institutional-grade reporting.',
      imageUrl: '/images/transparency.png',
    },
  },
  {
    key: 'about_registration',
    order: 5,
    data: {
      title: 'Quick registration, minimal needed.',
      description:
        'Access opportunities in a few minutes with a streamlined onboarding experience.',
      imageUrl: '/images/registration.png',
    },
  },
  {
    key: 'testimonials',
    order: 6,
    data: {
      eyebrow: 'TÉMOIGNAGES',
      title: 'Ils en parlent mieux que nous.',
      description:
        'Des investisseurs institutionnels et particuliers partagent leur expérience avec la plateforme.',
      items: [
        { name: 'Paul N.', text: 'Great investment platform.', rating: 5 },
        { name: 'Sarah M.', text: 'Very transparent and easy.', rating: 5 },
        { name: 'John D.', text: 'High quality projects.', rating: 5 },
      ],
    },
  },
  {
    key: 'faq',
    order: 7,
    data: {
      title: 'FAQ',
      subtitle: 'Frequently Asked Questions',
      items: [
        {
          id: 'faq-1',
          question: 'What is an Arquantix vault?',
          answerMarkdown:
            'A vault is a smart contract where you deposit stablecoins (USDC or USDT on Base). Your capital is deployed into a real estate project managed by Arquantix. Yield accrues automatically and is reflected in the price of your participation token, which grows over time.',
        },
        {
          id: 'faq-2',
          question: 'What returns can I expect?',
          answerMarkdown:
            'Each vault displays its fixed annual return (APR) upfront. Returns vary by project — typically between 7% and 11% APR depending on the asset, location, and duration. Yield is generated by the underlying real estate operation, not by speculation.',
        },
        {
          id: 'faq-3',
          question: 'How do I deposit and withdraw?',
          answerMarkdown:
            'Connect your wallet on Base, choose a vault, and deposit USDC or USDT. Withdrawals are available subject to a liquidity reserve maintained in each vault. Depending on the vault, an exit fee or notice period may apply — all terms are displayed before you deposit.',
        },
        {
          id: 'faq-4',
          question: 'Is my capital guaranteed?',
          answerMarkdown:
            'No. Like any investment, your capital is at risk. However, every vault is backed by a tangible real estate asset managed by Arquantix. The team\'s track record, project transparency, and on-chain reporting are designed to give you visibility and confidence — but they do not constitute a guarantee.',
        },
        {
          id: 'faq-5',
          question: 'Who can invest and how do I get started?',
          answerMarkdown:
            'Arquantix vaults are accessible worldwide. Registration is fast — a simplified KYC process lets you get started in minutes. Once onboarded, you connect your wallet and access all available opportunities directly from the platform. Our dedicated team ensures professional follow-up at every stage, with a built-in support function to guide you from first deposit to portfolio monitoring.',
        },
      ],
    },
  },
  {
    key: 'cta',
    order: 8,
    data: {
      title: 'Ready to Earn on Premium Real Assets?',
      description:
        'Create an account or connect a wallet, explore our projects, and start earning yield backed by premium real estate. In minutes.',
      primaryButtonText: 'Get started',
      primaryButtonHref: '/signup',
      secondaryButtonText: 'Explore vaults',
      secondaryButtonHref: '/vaults',
      backgroundColor: '#141208',
      overlayOpacity: 0.55,
    },
  },
  {
    key: 'footer',
    order: 9,
    data: {
      copyright: '© 2026 Arquantix',
      description: 'Institutional real estate investment platform',
    },
  },
]

async function main() {
  const page = await prisma.page.upsert({
    where: { slug: PAGE_SLUG },
    update: {
      urlPath: '/',
      title: 'Fractional Real Estate',
      description: 'Institutional real estate investment platform',
      themeColor: 'light',
      template: 'homepage',
    },
    create: {
      slug: PAGE_SLUG,
      urlPath: '/',
      title: 'Fractional Real Estate',
      description: 'Institutional real estate investment platform',
      themeColor: 'light',
      template: 'homepage',
    },
  })

  console.log(`Page OK: ${page.slug} → ${page.urlPath}`)

  for (const def of SECTIONS) {
    const section = await prisma.section.upsert({
      where: {
        pageId_key: { pageId: page.id, key: def.key },
      },
      update: { order: def.order, schemaVersion: 'v1' },
      create: {
        pageId: page.id,
        key: def.key,
        order: def.order,
        schemaVersion: 'v1',
      },
    })

    await prisma.sectionContent.upsert({
      where: {
        sectionId_locale_status: {
          sectionId: section.id,
          locale: 'fr',
          status: ContentStatus.PUBLISHED,
        },
      },
      update: { data: def.data as Prisma.InputJsonValue },
      create: {
        sectionId: section.id,
        locale: 'fr',
        status: ContentStatus.PUBLISHED,
        data: def.data as Prisma.InputJsonValue,
      },
    })

    console.log(`  section ${def.order} ${def.key}`)
  }

  console.log('Done. Homepage CMS: slug=home → /')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
