"""Question IDs for chatbot_epargne."""

Q_PROJECT_TYPE = "Q_PROJECT_TYPE"
Q_GOAL_PICK = "Q_GOAL_PICK"
Q_GOAL_FREE = "Q_GOAL_FREE"
Q_GOAL_CLARIFY = "Q_GOAL_CLARIFY"
Q_GOAL_FORCE_PICK = "Q_GOAL_FORCE_PICK"
Q_PROJECT_DETAILS = "Q_PROJECT_DETAILS"
