/** Labels pour les assets crypto (ticker -> libellé), partagé entre related-search et article links. */
export const ASSET_LABELS: Record<string, string> = {
  btc: 'Bitcoin (BTC)',
  eth: 'Ethereum (ETH)',
  sol: 'Solana (SOL)',
  xrp: 'XRP (XRP)',
  bnb: 'BNB (BNB)',
  ada: 'Cardano (ADA)',
  doge: 'Dogecoin (DOGE)',
  usdt: 'Tether (USDT)',
  usdc: 'USD Coin (USDC)',
  avax: 'Avalanche (AVAX)',
  link: 'Chainlink (LINK)',
  dot: 'Polkadot (DOT)',
  trx: 'Tron (TRX)',
  matic: 'Polygon (MATIC)',
  uni: 'Uniswap (UNI)',
  atom: 'Cosmos (ATOM)',
  ltc: 'Litecoin (LTC)',
  near: 'NEAR Protocol (NEAR)',
  apt: 'Aptos (APT)',
  arb: 'Arbitrum (ARB)',
  op: 'Optimism (OP)',
  inj: 'Injective (INJ)',
  sui: 'Sui (SUI)',
  sei: 'Sei (SEI)',
  fil: 'Filecoin (FIL)',
  etc: 'Ethereum Classic (ETC)',
  xlm: 'Stellar (XLM)',
  algo: 'Algorand (ALGO)',
  vet: 'VeChain (VET)',
  icp: 'Internet Computer (ICP)',
  ftm: 'Fantom (FTM)',
  hbar: 'Hedera (HBAR)',
  cro: 'Cronos (CRO)',
  sand: 'The Sandbox (SAND)',
  mana: 'Decentraland (MANA)',
  axs: 'Axie Infinity (AXS)',
}
