"""
Assemble final EmailSpec from template entity + body spec + modules
Header/Footer modules are imposed; AI only fills body + hero props
"""
from typing import Optional, List, Tuple, Dict, Any, Callable
from .schemas import EmailSpec, Block
from .lock import enforce_locked_structure, extract_structure


def assemble_email(
    template_entity: Dict[str, Any],
    body_spec: EmailSpec,
    locale: str,
    modules_resolver: Callable[[str, str], Optional[EmailSpec]],
) -> Tuple[EmailSpec, List[str]]:
    """
    Assemble final EmailSpec from template + body spec + modules
    
    Rules:
    - HEADER/FIXED/FOOTER blocks come exclusively from modules, never from AI
    - AI spec is only allowed to fill:
      - HERO props (title/subtitle/cta + image_url)
      - BODY blocks defined by template.bodyTemplate
    - Use lock logic to enforce body structure
    
    Args:
        template_entity: EmailTemplateEntity dict with headerModuleId, footerModuleId, bodyTemplate, lockPolicy
        body_spec: EmailSpec generated by AI (contains HERO + BODY blocks only)
        locale: Target locale for module localization
        modules_resolver: Function (module_id, locale) -> EmailSpec | None
    
    Returns:
        (final_spec, warnings)
    """
    warnings: List[str] = []
    final_blocks: List[Block] = []
    
    # 1. Load HEADER module (localized)
    header_module_id = template_entity.get("headerModuleId")
    if header_module_id:
        header_module = modules_resolver(header_module_id, locale)
        if header_module and header_module.blocks:
            # Header blocks come from module - filter to only header blocks
            header_blocks = [b for b in header_module.blocks if b.type == "header"]
            if header_blocks:
                final_blocks.extend(header_blocks)
            else:
                warnings.append(f"Header module {header_module_id} has no header blocks")
        else:
            warnings.append(f"Header module {header_module_id} not found or empty, skipping")
    else:
        warnings.append("No header module specified in template")
    
    # 2. HERO block (from AI spec, but structure fixed by template)
    # Find HERO block in body_spec
    hero_block = None
    body_blocks_for_template = []
    for block in body_spec.blocks:
        if block.type == "hero":
            hero_block = block
        else:
            # Other blocks are part of body template
            body_blocks_for_template.append(block)
    
    # Hero is required or optional based on heroPolicy
    hero_policy = template_entity.get("heroPolicy", "REQUIRED")
    if hero_policy == "REQUIRED" and not hero_block:
        warnings.append("Hero block required but not provided in body spec")
    elif hero_block:
        # Hero structure is fixed; only props can vary
        # Validate hero structure matches template expectations
        final_blocks.append(hero_block)
    
    # 3. BODY blocks (from AI spec, constrained by bodyTemplate/lockPolicy)
    # Note: bodyStarterModuleId is handled in routes.py _create_body_spec_from_template
    # here we just process the body_spec provided by AI
    body_template = template_entity.get("bodyTemplate", {})
    lock_policy = template_entity.get("lockPolicy", {})
    
    if body_template and lock_policy:
        # Apply lock logic to body blocks only
        body_email_spec = EmailSpec(
            subject=body_spec.subject,  # Use body spec subject as base
            preheader=body_spec.preheader,
            locale=locale,
            theme=body_spec.theme,
            blocks=body_blocks_for_template,
        )
        
        # Create base spec from bodyTemplate for lock enforcement
        base_body_blocks = _create_base_blocks_from_template(body_template)
        base_body_spec = EmailSpec(
            subject=body_spec.subject,
            preheader=body_spec.preheader,
            locale=locale,
            theme=body_spec.theme,
            blocks=base_body_blocks,
        )
        
        # Enforce locked structure on body
        locked_body_spec, lock_warnings = enforce_locked_structure(
            base_body_spec, body_email_spec
        )
        warnings.extend(lock_warnings)
        final_blocks.extend(locked_body_spec.blocks)
    else:
        # No body template lock; use body blocks as-is
        final_blocks.extend(body_blocks_for_template)
    
    # 4. FIXED modules (LEGAL/SIGNATURE/etc.)
    fixed_module_ids = template_entity.get("fixedModuleIds", [])
    if isinstance(fixed_module_ids, list):
        for fixed_module_id in fixed_module_ids:
            fixed_module = modules_resolver(fixed_module_id, locale)
            if fixed_module and fixed_module.blocks:
                final_blocks.extend(fixed_module.blocks)
            else:
                warnings.append(f"Fixed module {fixed_module_id} not found or empty")
    
    # 5. FOOTER module (localized)
    footer_module_id = template_entity.get("footerModuleId")
    if footer_module_id:
        footer_module = modules_resolver(footer_module_id, locale)
        if footer_module and footer_module.blocks:
            # Footer blocks come from module - filter to only footer blocks
            footer_blocks = [b for b in footer_module.blocks if b.type == "footer"]
            if footer_blocks:
                final_blocks.extend(footer_blocks)
            else:
                warnings.append(f"Footer module {footer_module_id} has no footer blocks")
                # Fallback: create minimal footer with unsubscribe placeholder
                from .schemas import FooterBlock
                fallback_footer = FooterBlock(
                    type="footer",
                    variant="default",
                    company_name="Company",
                    unsubscribe_url_placeholder="{{unsubscribe_url}}",
                )
                final_blocks.append(fallback_footer)
        else:
            warnings.append(f"Footer module {footer_module_id} not found or empty")
            # Fallback: create minimal footer with unsubscribe placeholder
            from .schemas import FooterBlock
            fallback_footer = FooterBlock(
                type="footer",
                variant="default",
                company_name="Company",
                unsubscribe_url_placeholder="{{unsubscribe_url}}",
            )
            final_blocks.append(fallback_footer)
    else:
        warnings.append("No footer module specified in template")
        # Fallback footer
        from .schemas import FooterBlock
        fallback_footer = FooterBlock(
            type="footer",
            variant="default",
            company_name="Company",
            unsubscribe_url_placeholder="{{unsubscribe_url}}",
        )
        final_blocks.append(fallback_footer)
    
    # Build final spec
    final_spec = EmailSpec(
        subject=body_spec.subject,
        preheader=body_spec.preheader,
        locale=locale,
        theme=body_spec.theme or template_entity.get("theme", "arquantix_v1"),
        blocks=final_blocks,
    )
    
    return final_spec, warnings


def _create_base_blocks_from_template(body_template: Dict[str, Any]) -> List[Block]:
    """
    Create base blocks from bodyTemplate definition
    bodyTemplate should define: core_blocks, optional_slots
    """
    blocks: List[Block] = []
    
    # Parse body_template structure
    core_blocks = body_template.get("core_blocks", [])
    for block_def in core_blocks:
        block = _block_def_to_block(block_def)
        if block:
            blocks.append(block)
    
    return blocks


def _block_def_to_block(block_def: Dict[str, Any]) -> Optional[Block]:
    """Convert block definition dict to Block instance"""
    block_type = block_def.get("type")
    variant = block_def.get("variant", "default")
    
    # Import block classes
    from .schemas import (
        HeroBlock, SectionTitleBlock, TextBlock, BulletsBlock,
        FeatureCardsBlock, ImageBlock, CtaBlock, DividerBlock,
        SpacerBlock, FooterBlock,
    )
    
    block_classes = {
        "hero": HeroBlock,
        "section_title": SectionTitleBlock,
        "text": TextBlock,
        "bullets": BulletsBlock,
        "feature_cards": FeatureCardsBlock,
        "image": ImageBlock,
        "cta": CtaBlock,
        "divider": DividerBlock,
        "spacer": SpacerBlock,
        "footer": FooterBlock,
    }
    
    block_class = block_classes.get(block_type)
    if not block_class:
        return None
    
    # Create block with default props from block_def
    props = block_def.get("props", {})
    try:
        # Use variant from block_def
        props["variant"] = variant
        return block_class(**props)
    except Exception as e:
        # Fallback: create minimal block
        try:
            return block_class(type=block_type, variant=variant)
        except:
            return None

